### ISSUE TITLE
Robot images are badly squished on mobile

### ISSUE THREAD

**Issue by willgames-afk** [beavertronics/5970#3]
For narrow browsers (ie on mobile), the robot images become squished horizontally- see below image.

![image](https://github.com/beavertronics/5970/assets/69923277/e14341e9-2453-4297-a411-9d58c40417c7)

**Comment by SketchedDoughnut** [comment]
Ah yes, this- besides the home page, the other pages do not have compatibility for mobile users. It's something I initially asked Collin to fix, but I don't know when that might happen.

**Comment by SketchedDoughnut** [comment]
fixed! I designed a mobile version of this page which fixes the issue.
